name: update-flake-lock
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 0 1 * *' # At 00:00 on first day of month.

jobs:
  repos:
    runs-on: ubuntu-latest
    outputs:
       matrix: ${{ steps.setmatrix.outputs.matrix }}
    steps:
    - name: checkout source code
      uses: actions/checkout@v3
    - id: setmatrix
      run: |
        cat repos.md | grep "^-" | sed -E "s/- (.+)/\"\1\"/" | jq -sc "{ \"repo\": . }" > tmp
        matrixStringifiedObject=$(cat ./tmp) # Use this as jq @sh not working right
        echo "::set-output name=matrix::$matrixStringifiedObject"

  lockfile:
    runs-on: ubuntu-latest
    needs:
      repos
    strategy:
       fail-fast: false
       matrix: ${{fromJson(needs.repos.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ matrix.repo }}
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v1
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v23
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          pr-title: "Update flake.lock" # Title of PR to be created
          pr-labels: |                  # Labels to be set on the PR
            dependencies
            automated
          branch: "update/flake-lock"
